### ISSUE TITLE
Add recommended sgminer/ccminer build links

### ISSUE THREAD

**Issue by Tajnymag** [thatguywiththatname/GarlicGUI#2]
Please, could you add recommended sgminer/ccminer build links, or even better, make possible to auto download them if missing?

**Comment by thatguywiththatname** [comment]
Sounds good, where would you suggest putting the links? In the readme? When you launch the app for the first time?

**Comment by Tajnymag** [comment]
Probably both:
* in README as a requirement in **Instructions**
* in the app a button for downloading the latest version from Github

**Comment by thatguywiththatname** [comment]
Info added to readme and link to readme added below the title in the app,
Thanks for the suggestion
